/* eslint-disable */
require('./arrow-left')
require('./arrow-right')
require('./case')
require('./check-filled')
require('./check')
require('./doble-arrow')
require('./facebook')
require('./google-plus')
require('./group')
require('./job')
require('./like')
require('./m-glass')
require('./pinterest')
require('./translate')
require('./twitter')
require('./wave-shape')
